// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetScape.Modules.DAL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GoogleSearchScrape.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210129032859_AddInitial")]
    partial class AddInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GoogleSearchScrape.Abstractions.Model.ScrapeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("GoogleSearchScrape.Abstractions.Model.TimedScrapeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset?>("LastRequest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxResults")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RepeatTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("GoogleSearchScrape.Abstractions.Model.ScrapeResult", b =>
                {
                    b.HasOne("GoogleSearchScrape.Abstractions.Model.TimedScrapeRequest", "Request")
                        .WithMany("ScrapeResults")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GoogleSearchScrape.Abstractions.Model.TimedScrapeRequest", b =>
                {
                    b.Navigation("ScrapeResults");
                });
#pragma warning restore 612, 618
        }
    }
}
